"""empty message

Revision ID: c17fed8eea6b
Revises: d2330648c758
Create Date: 2019-12-17 17:09:58.545000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c17fed8eea6b'
down_revision = 'd2330648c758'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('l_final', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('l_quarterfinal', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('l_semifinal', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('real_final', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('real_third', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match', 'real_third')
    op.drop_column('match', 'real_final')
    op.drop_column('match', 'l_semifinal')
    op.drop_column('match', 'l_quarterfinal')
    op.drop_column('match', 'l_final')
    # ### end Alembic commands ###
