"""empty message

Revision ID: d2330648c758
Revises: 
Create Date: 2019-12-16 20:21:05.325200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2330648c758'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('final', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('quarterfinal', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('semifinal', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('third', sa.Integer(), nullable=True))
    op.add_column('played_match', sa.Column('final', sa.Integer(), nullable=True))
    op.add_column('played_match', sa.Column('quarterfinal', sa.Integer(), nullable=True))
    op.add_column('played_match', sa.Column('semifinal', sa.Integer(), nullable=True))
    op.add_column('played_match', sa.Column('third', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('played_match', 'third')
    op.drop_column('played_match', 'semifinal')
    op.drop_column('played_match', 'quarterfinal')
    op.drop_column('played_match', 'final')
    op.drop_column('match', 'third')
    op.drop_column('match', 'semifinal')
    op.drop_column('match', 'quarterfinal')
    op.drop_column('match', 'final')
    # ### end Alembic commands ###
